#!/bin/bash

ROOTDIR=`pwd`

#echo "We're in:" $ROOTDIR

# TODO
#sudo apt-get update
#sudo apt-get upgrade

#sudo apt-get install cmake minicom screen python-serial autoconf libusb-1.0-0-dev
#sudo ./release_serial.sh
#sudo ./install_node.sh
#sudo ./install_stlink

cleanup()
{
	echo "CLEANUP"
	cd scripts
	./cleanup.sh
	cd ..
}

install_node()
{
	echo "INSTALL NODE"
	cd bin
	./install_node.sh
	cd ..
}

update_esp_cli()
{
	echo "UPDATE ESP_CLI"
	cd src
	./update_esp_cli.sh
	cd ..
}

update_cmsis_stdperiph()
{
	echo "UPDATE CMSIS STDPERIPH"
	cd src
	./update_cmsis_stdperiph.sh
	cd ..
}

update_espruino()
{
	echo "UPDATE ESPRUINO"
	cd src
	./update_espruino.sh
	cd ..
}

release_serial()
{
	echo "RELEASE SERIAL"
	cd scripts
	./release_serial.sh
	cd ..
}

path_env()
{
	echo "SET PATH ENV"
	cd scripts
	./path_env.sh
	cd ..
}

update_self()
{
	echo "UPDATE SELF"
	git pull
	
	if [ -d /opt/arminarm ]; then
		echo "Directory exists: updating"
	else
		echo "Tools don't exist: installing"
		cd bin
		./install_toolchain.sh
		cd ..
	fi


	if [ -d /opt/arminarm/tools ]; then
		echo "Directory exists: updating"
		cd src
		sudo cp -r tools /opt/arminarm/
		cd ..
	else
		echo "Tools don't exist: installing"
		cd src
		sudo cp -r tools /opt/arminarm/
		cd ..
	fi
	
}




show_options()
{
	echo ""
	echo "#############################################################"
	echo "#                        ARMinARM                           #"
	echo "#############################################################"
	echo ""
	echo "	0)	Update/Install ARMinARM Toolchain"
	echo "	1)	Add /opt/arminarm* to PATH env"
	echo "	2)	Release Serial port /dev/ttyAMA0"
	echo "	3)	Install CMSIS_StdPeriph Examples"
	echo "	4)	Install node.js"
#	echo ""
	echo "	5)	Update/Install Espruino Source code"
	echo "	6)	Update/Install esp-cli"
	echo "	7)	Clean up"
	echo ""
	echo "	q)	Quit"
	echo ""
}


OPTION="0"

while [ "$OPTION" != "q" ]; do

	show_options

	echo "Enter your choice:"
	read OPTION

	if [ "$OPTION" == "0" ]; then
		update_self
		OPTION="q"
		echo "Updated. Please run setup again."
	elif [ "$OPTION" == "1" ]; then
		path_env
	elif [ "$OPTION" == "2" ]; then
		release_serial
	elif [ "$OPTION" == "3" ]; then
		update_cmsis_stdperiph
	elif [ "$OPTION" == "4" ]; then
		install_node
	elif [ "$OPTION" == "5" ]; then
		update_espruino
	elif [ "$OPTION" == "6" ]; then
		update_esp_cli
	elif [ "$OPTION" == "7" ]; then
		cleanup
	elif [ "$OPTION" == "q" ]; then
		echo "Bye!"
	else
		echo "'$OPTION' is an unkown option."
	fi

done



#sudo apt-get update
#sudo apt-get upgrade

