#!/bin/bash

#ROOTDIR=`pwd`

#sudo apt-get update
#sudo apt-get upgrade
#sudo apt-get install -y cmake minicom screen python-serial autoconf libusb-1.0-0-dev libtool libftdi-dev texinfo


cleanup()
{
	echo "CLEANUP"
	cd scripts
	./cleanup.sh
	cd ..
}

install_node()
{
	echo "INSTALL NODE"
	cd bin
	./install_node.sh
	cd ..
}

update_esp_cli()
{
	echo "UPDATE ESP_CLI"
	cd src
	./update_esp_cli.sh
	cd ..
}

update_elua()
{
	echo "UPDATE ELUA"
	cd src
	./update_elua.sh
	cd ..
}

update_cmsis_stdperiph()
{
	echo "UPDATE CMSIS STDPERIPH"
	cd src
	./update_cmsis_stdperiph.sh
	cd ..
}

update_espruino()
{
	echo "UPDATE ESPRUINO"
	cd src
	./update_espruino.sh
	cd ..
}

update_libmaple()
{
	echo "UPDATE LIBMAPLE"
	cd src
	./update_libmaple.sh
	cd ..
}

update_libopencm3()
{
	echo "UPDATE LIBOPENCM3"
	cd src
	./update_libopencm3.sh
	cd ..
}

update_openocd()
{
	echo "UPDATE OPENOCD"
	cd src
	./update_openocd.sh
	cd ..
}

update_stlink()
{
	echo "UPDATE STLINK"
	cd src
	./update_stlink.sh
	cd ..
}

release_serial()
{
	echo "RELEASE SERIAL"
	cd scripts
	sudo ./release_serial.sh
	cd ..
}

path_env()
{
	echo "SET PATH ENV"
	cd scripts
	./path_env.sh
	cd ..
}

upload_espruino()
{
	echo "UPLOADING ESPRUINO.BIN"
	cd bin
	./install_espruino_bin.sh
	echo "espruino communicates on 9600 baud on /dev/ttyAMA0"
	cd ..
}

upload_elua()
{
	echo "UPLOADING ELUA.BIN"
	cd bin
	./install_elua_bin.sh
	echo "eLua communicates on 115200 baud on /dev/ttyAMA0"
	cd ..
}

update_toolchain()
{
	update_self

	echo "UPDATE TOOLCHAIN"
	if [ -d /opt/arminarm ]; then
		echo "Directory exists: updating"
	fi

	cd bin
	./install_toolchain.sh
	cd ..

	if [ -d /opt/arminarm/tools ]; then
		echo "Directory exists: updating"
	else
		echo "Tools not found: installing"
	fi

	cd src
	sudo cp -r tools /opt/arminarm/
	cd ..
}

update_self()
{
	echo "UPDATE SELF"
	git pull
}




show_options()
{
	echo ""
	echo "#############################################################"
	echo "#                        ARMinARM                           #"
	echo "#############################################################"
	echo ""
	echo "	0) Update Self"
	echo "	1) Update/Install ARMinARM GCC Toolchain"
	echo "	2) Add /opt/arminarm* to PATH env"
	echo "	3) Release Serial port /dev/ttyAMA0"
	echo "	4) Update/Install node.js"
	echo ""
	echo "	a) Update/Install CMSIS_StdPeriph Examples"
	echo "	b) Update/Install Espruino source code"
	echo "	c) Update/Install esp-cli"
	echo "	d) Update/Install eLua source code"
	echo "	e) Update/Install libmaple"
	echo "	f) Update/Install libopencm3"
	echo "	g) Update/Install OpenOCD"
	echo "	h) Update/Install ST-Link"
	echo ""
	echo "	m) Upload espruino.bin to ARMinARM board"
	echo "	n) Upload elua.bin to ARMinARM board"
	echo ""
	echo "	q) Quit"
	echo ""
}


OPTION="0"

while [ "$OPTION" != "q" ]; do

	show_options

	echo "Enter your choice:"
	read OPTION

	if [ "$OPTION" == "0" ]; then
		update_self
		OPTION="q"
		echo "Updated. Please run setup again."
	elif [ "$OPTION" == "1" ]; then
		update_toolchain
	elif [ "$OPTION" == "2" ]; then
		path_env
	elif [ "$OPTION" == "3" ]; then
		release_serial
	elif [ "$OPTION" == "4" ]; then
		install_node
	elif [ "$OPTION" == "a" ]; then
		update_cmsis_stdperiph
	elif [ "$OPTION" == "b" ]; then
		update_espruino
	elif [ "$OPTION" == "c" ]; then
		update_esp_cli
	elif [ "$OPTION" == "d" ]; then
		update_elua
	elif [ "$OPTION" == "e" ]; then
		update_libmaple
	elif [ "$OPTION" == "f" ]; then
		update_libopencm3
	elif [ "$OPTION" == "g" ]; then
		update_openocd
	elif [ "$OPTION" == "h" ]; then
		update_stlink


	elif [ "$OPTION" == "m" ]; then
		upload_espruino
	elif [ "$OPTION" == "n" ]; then
		upload_elua


	elif [ "$OPTION" == "z" ]; then
		cleanup
	elif [ "$OPTION" == "q" ]; then
		echo "Bye!"
	else
		echo "'$OPTION' is an unkown option."
	fi

done
