#!/bin/bash

TOOLS=/opt/arminarm/tools

if [ "$1" == "reset" ]; then
	sudo $TOOLS/stm32loader.py -p /dev/ttyAMA0 -t
elif [ "$1" == "bootloader" ]; then
	sudo $TOOLS/stm32loader.py -p /dev/ttyAMA0 -o
elif [ "$1" == "flash" ]; then
	sudo $TOOLS/stm32loader.py -p /dev/ttyAMA0 -e -v -w $2
elif [ "$1" == "openocd" ]; then
	sudo openocd -s /usr/share/openocd/scripts -f /opt/arminarm/tools/arminarm.tcl
else
	echo "'$1' is an unkown option."
fi
